### ISSUE TITLE
Adding a scope to Google OAuth Connection causes array_merge error

### ISSUE THREAD

**Issue by carterheron** [verbb/consume#3]
### Describe the bug

I setup a Google OAuth Connection following the guide listed [here](https://verbb.io/craft-plugins/consume/docs/providers/all-providers#google). If I omit the OAuth scopes for this provider I am able to successfully connect, however, for this application, I need the token to be assigned with specific scope privileges and as soon as I add a scope in, (for example _https://www.googleapis.com/auth/analytics.readonly_) It refuses to connect. I added a debug statement in the source code and found that this seems to be caused by this error: 

`“array_merge(): Argument #2 must be of type array, string given” /var/www/html/vendor/verbb/auth/src/clients/google/provider/Google.php:75.`

<img width="582" alt="Google" src="https://github.com/verbb/consume/assets/58057403/b1c08fec-902d-4622-9cc1-a2984d7f171f">

Turns out $options['scope'] always returns a string, even if additional scopes are added within the control panel (thus always causing the array_merge error). 

### Steps to reproduce

1. Setup a craft 4 build (4.4.15)
2. Install Consume Plugin
3. Follow instructions to create a Google OAuth Client [here](https://verbb.io/craft-plugins/consume/docs/providers/all-providers#google)
4. Add an additional scope
5. Test connection

### Craft CMS version

4.4.15

### Plugin version

1.0.3

### Multi-site?

No

### Additional context

Checking my database, the object settings column contains the object : `{"proxyRedirect":"$DEV_MODE","clientId":"$CONSUME_GA_CLIENT_ID","clientSecret":"$CONSUME_GA_SECRET","scopes":["https:\/\/www.googleapis.com\/auth\/analytics.readonly"]}`

The web logs contain the object:
`'verbb\\consume\\clients\\oauth\\Google' => [
            'clientId' => '$CONSUME_GA_CLIENT_ID'
            'clientSecret' => '••••••••••••••••••'
            'scopes' => [
                0 => [
                    'scope' => 'https://www.googleapis.com/auth/analytics.readonly'
                ]
            ]
            'proxyRedirect' => '$DEV_MODE'
        ]`

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/consume:"dev-craft-4 as 1.0.3"`

**Comment by carterheron** [comment]
Awesome, much appreciated!

**Comment by engram-design** [comment]
Fixed in [1.0.4](https://github.com/verbb/consume/releases/tag/1.0.4)
