### ISSUE TITLE
Client provider URL adds a trailing slash

### ISSUE THREAD

**Issue by ammonhaggerty** [verbb/consume#5]
### Describe the bug

Some APIs have a URL with no trailing slash (e.g., https://api.openai.com/v1/chat/completions). When the client is referenced the trailing slash is added, which results in a 404 in the case of OpenAI.

### Steps to reproduce

1. Add generic Credential client
2. Add a URL without a trailing slash 
3. Reference the client in a 'consume.fetchData' call

### Craft CMS version

4.5.11.1

### Plugin version

1.0.4

**Comment by engram-design** [comment]
Fixed in [Auth 1.0.12](https://github.com/verbb/auth/releases/tag/1.0.12)
