### ISSUE TITLE
Fedex Authorization API

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/consume#6]
### What are you trying to do?

Hello,

Looking at the doc for the [Fedex API](https://developer.fedex.com/api/en-us/catalog/authorization/docs.html) it looks like I can't use the Generic provider, as Fedex requires a json payload with client credentials.

Using postman I can get the token by using those settings:
<img width="525" alt="Screenshot 2023-12-15 at 15 23 00" src="https://github.com/verbb/consume/assets/1942313/c691d450-d83a-48a2-b425-10b5701ff24f">

### What's your proposed solution?

Implement a Fedex provider, or tell me where I'm not doing things properly :)

**Comment by engram-design** [comment]
Good point that we don't handle different grants at the moment. I've just added that for the generic OAuth client.

However, Fedex is also a _little_ particular that it needs its own specific provider setup, which I've also added.

See [1.0.6](https://github.com/verbb/consume/releases/tag/1.0.6)

**Comment by bleepsandblops** [comment]
@engram-design thank you so much!
